1 4 friends
faceitruby/fellow_driver pull request #14
Opened 2020-04-13 14:18 UTC by tymosVS

https://app.asana.com/0/1159181417647996/1162628642777106

2020-04-13 14:36 UTC, drkmen commented
Please name PR's correctly.

2020-04-14 10:21 UTC, drkmen requested changes

2020-04-14 10:21 UTC, drkmen commented on app/controllers/facebook_friends_controller.rb
> +    result = TrustedDrivers::FacebookFriendsListService.perform(
One of a main reasons of proper naming is to understand what is service doing by his name. 
Looking at `TrustedDrivers::FacebookFriendsListService` i can't be sure what exactly this service does. 
So, do not hesitate to use name spaces and do like this:
```ruby
module TrustedDrivers
  module Facebook
    class FetchFriendsService # if that class should return facebook friends
```

Anyway, the name of service must represent his main purpose. I.e fetch, update, create and so on.

2020-04-14 10:21 UTC, drkmen commented on app/controllers/trusted_driver_requests_controller.rb
> +    result = TrustedDrivers::Requests::CreateService.perform(trusted_driver_requests_params.merge({ current_user: current_user }))
redundant curly brackets

2020-04-14 10:21 UTC, drkmen commented on app/controllers/trusted_driver_requests_controller.rb
> +    render_success_response(TrustedDrivers::Requests::DeleteService.perform(trusted_driver_request).data, :no_content)
All services must receive Hash as an argument. 
```ruby
.perform(trusted_driver: trusted_driver_request)
```

2020-04-14 10:21 UTC, drkmen commented on app/controllers/trusted_drivers_controller.rb
> +  def trusted_drivers
it should have been index, right?

2020-04-14 10:21 UTC, drkmen commented on app/controllers/trusted_drivers_controller.rb
> +    TrustedDriverRequest.find(trusted_driver_params[:id])
it's not important to use strong params when you are fetching records from DB
just FYI

2020-04-14 10:21 UTC, drkmen commented on app/models/trusted_driver.rb
> +  belongs_to :trusted_driver, class_name: :User
better to use String when a word start with a capital letter

2020-04-14 10:21 UTC, drkmen commented on app/models/user.rb
> +    first_name.to_s + ' ' + last_name.to_s
is it necessary converting to string?

2020-04-14 10:21 UTC, drkmen commented on app/presenters/car_presenter.rb
> +    end
in `ApplicationPresenter` add:
```ruby
def url_helpers
  Rails.application.routes.url_helpers
end

# and here:
properties.merge(picture: url_helpers.rails_blob_path(record.picture, only_path: true)) if record.picture.attached?
```

2020-04-14 10:21 UTC, drkmen commented on app/presenters/trusted_driver_request_presenter.rb
> +    User.find(properties[:requestor_id]).present.page_context.slice(:id, :email, :avatar, :first_name, :last_name, :phone)
don't need of use `properties` method, because you already have `record` with `.requestor_id`
calling `#properties` just making additional code iterations

2020-04-14 10:21 UTC, drkmen commented on app/presenters/user_presenter.rb
> +                        remember_created_at created_at updated_at jti provider uid first_name last_name address invitation_token invitation_created_at invitation_sent_at invitation_accepted_at invita
do not forget to use rubocop
this line is to long

2020-04-14 10:21 UTC, drkmen commented on app/presenters/user_presenter.rb
> +    end
same as was above

2020-04-14 10:21 UTC, drkmen commented on app/services/trusted_drivers/create_service.rb
> +      trusted_driver_request[:receiver_id] if trusted_driver_request
`trusted_driver_request` is an instance of `TrustedDriversRequest`, right? If so, please use methods to get attributes.
I.e `trusted_driver_request.receiver_id`

2020-04-14 10:21 UTC, drkmen commented on app/services/trusted_drivers/create_service.rb
> +        # current_user.trusted_drivers << trusted_driver
?

2020-04-14 10:21 UTC, drkmen commented on app/services/trusted_drivers/create_service.rb
> +        TrustedDrivers::Requests::DeleteService.perform(trusted_driver_request)
i don't thing we should delete accepted requests

2020-04-14 10:21 UTC, drkmen commented on app/services/trusted_drivers/create_service.rb
> +      trusted_driver_request[:requestor_id] if trusted_driver_request
`trusted_driver_request&.requestor_id `

2020-04-14 10:21 UTC, drkmen commented on app/services/trusted_drivers/facebook_friends_list_service.rb
> +    rescue StandardError => e
do not rescue from `StandardError`
that may cause user will see internal exceptions which his should not see

2020-04-14 10:21 UTC, drkmen commented on app/services/trusted_drivers/facebook_friends_list_service.rb
> +      params[:near].presence == 'true'
```ruby
ActiveRecord::Type::Boolean.new.cast(params[:near].presence)
```

2020-04-14 10:21 UTC, drkmen commented on app/services/trusted_drivers/facebook_friends_list_service.rb
> +      end
```ruby
return true unless current_user.address && friend.address

current_adress = Geocoder.search(current_user.address)[0].coordinates
friend_adress = Geocoder.search(friend.address)[0].coordinates
Geocoder::Calculations.distance_between(current_adress, friend_adress) < 25
```

2020-04-14 10:21 UTC, drkmen commented on app/services/trusted_drivers/messages/create_service.rb
> +        #{link}"
use `heredoc` for multilines strings

2020-04-14 10:21 UTC, drkmen commented on app/services/trusted_drivers/user_search_service.rb
> +      @user = User.find_by(email: email) if email
use guard clause for all find_ methods

2020-04-14 10:21 UTC, drkmen commented on config/environments/development.rb
> +}
add tab

2020-04-14 10:21 UTC, drkmen commented on config/routes.rb
> +    get 'trusted_for', to: 'trusted_drivers#trusted_for'
put inside `resources :trusted_drivers` block
```ruby
resources :trusted_drivers, only: %i[create destroy] do
  get :trusted_drivers
  get :trusted_for
end
```

2020-04-14 10:21 UTC, drkmen commented on db/migrate/20200318121323_create_trusted_driver.rb
> +      t.integer :trust_driver_id
it's ok for now, but in future please use `t.references`

2020-04-14 10:21 UTC, drkmen commented on spec/controllers/trusted_driver_requests_controller_spec.rb
> +      request.headers['token'] = token
you can move `request.headers['token'] = token` above and do not repeat it in all request

2020-04-14 10:21 UTC, drkmen commented on app/services/trusted_drivers/facebook_friends_list_service.rb
> +      params[:near].presence == 'true'
```ruby
ActiveRecord::Type::Boolean.new.cast(params[:near].presence)
```

2020-04-14 10:21 UTC, drkmen commented on spec/services/trusted_drivers/create_service_spec.rb
> +
```ruby
describe '#call'
```

2020-04-14 10:21 UTC, drkmen commented on spec/services/trusted_drivers/create_service_spec.rb
> +      )
```ruby
let(:params) do
  {
    trusted_driver_request: trusted_driver_request,
    current_user: trusted_driver_request.receiver
  }
end

subject { described_class.perform(params) }
```

2020-04-14 10:21 UTC, drkmen commented on spec/services/trusted_drivers/create_service_spec.rb
> +      TrustedDrivers::CreateService.perform(trusted_driver_request: nil, current_user: trusted_driver_request.receiver)
here you will just redefine `params` instead of repeating code with a minimum difference

2020-04-14 10:21 UTC, drkmen commented on spec/services/trusted_drivers/create_service_spec.rb
> +end
follow next structure:
```ruby
RSpec.describe TrustedDrivers::CreateService do
  let(:params) do
    {
      trusted_driver_request: trusted_driver_request,
      current_user: trusted_driver_request.receiver
    }
  end

  subject { described_class.perform(params) }

  describe '#call' do
    context do
      let(:params) ...
      it
    end

    context do
      let(:params) ...
      it
    end
  end
end

2020-04-14 10:21 UTC, drkmen commented on spec/services/trusted_drivers/delete_service_spec.rb
> +  subject { TrustedDrivers::DeleteService.perform(trusted_driver: trusted_driver) }
same as above

2020-04-14 10:21 UTC, drkmen commented on spec/services/trusted_drivers/facebook_friends_list_service_spec.rb
> +end
the same

2020-04-14 10:21 UTC, drkmen commented on spec/services/trusted_drivers/messages/create_service_spec.rb
> +end
the same

2020-04-16 08:15 UTC, drkmen requested changes

2020-04-16 08:15 UTC, drkmen commented on app/services/trusted_drivers/create_service.rb
> +        trusted_driver_request.update(accepted: true)
use `update_attributes` or `update_attribute`

2020-04-16 08:15 UTC, drkmen commented on app/services/trusted_drivers/create_service.rb
> +        OpenStruct.new(success?: false, data: nil, errors: trusted_driver.errors)
since `trusted_driver` is a method which returns `TrustedDriver.new` are you sure that in errors will be something?

2020-04-16 08:15 UTC, drkmen commented on spec/controllers/trusted_driver_requests_controller_spec.rb
> +    before do
`before` block available without `context` or `describe`
please remove this `describe 'actions'`

2020-04-16 08:15 UTC, drkmen commented on spec/controllers/trusted_driver_requests_controller_spec.rb
> +      end
```ruby
before { send_request }
```

2020-04-16 08:15 UTC, drkmen commented on spec/controllers/trusted_driver_requests_controller_spec.rb
> +
?
also please to try to rethink 'not success' and 'success' contexts.

2020-04-16 08:15 UTC, drkmen commented on spec/controllers/trusted_driver_requests_controller_spec.rb
> +      end
`before { send_request }`

2020-04-16 08:15 UTC, drkmen commented on spec/controllers/trusted_drivers_controller_spec.rb
> +  end
?

2020-04-16 08:15 UTC, drkmen commented on spec/services/trusted_drivers/delete_service_spec.rb
> +  subject { TrustedDrivers::DeleteService.perform(params) }
described_class

2020-04-16 08:15 UTC, drkmen commented on spec/services/trusted_drivers/facebook/fetch_friends_service_spec.rb
> +  subject { TrustedDrivers::Facebook::FetchFriendsService.perform(params) }
use `described_class` instead of repeating everywhere class name

2020-04-16 08:15 UTC, drkmen commented on spec/services/trusted_drivers/facebook/fetch_friends_service_spec.rb
> +        allow_any_instance_of(TrustedDrivers::Facebook::FetchFriendsService).to receive(:friends_uid)
here

2020-04-16 08:15 UTC, drkmen commented on spec/services/trusted_drivers/facebook/fetch_friends_service_spec.rb
> +          allow_any_instance_of(TrustedDrivers::Facebook::FetchFriendsService).to receive(:in_radius?)
and here

2020-04-16 08:15 UTC, drkmen commented on spec/services/trusted_drivers/messages/create_service_spec.rb
> +  subject { TrustedDrivers::Messages::CreateService.perform(params) }
and here

2020-04-16 08:15 UTC, drkmen commented on spec/services/trusted_drivers/messages/create_service_spec.rb
> +          allow_any_instance_of(TrustedDrivers::Messages::CreateService).to receive(:token).and_return(token)
and here

2020-04-16 08:15 UTC, drkmen commented on spec/services/trusted_drivers/messages/prepare_message_service_spec.rb
> +  subject { TrustedDrivers::Messages::PrepareMessageService.perform(params) }
and here

2020-04-16 08:15 UTC, drkmen commented on spec/services/trusted_drivers/messages/prepare_message_service_spec.rb
> +    allow_any_instance_of(TrustedDrivers::Messages::PrepareMessageService).to receive(:send_phone_message)
and here

2020-04-16 08:15 UTC, drkmen commented on spec/services/trusted_drivers/messages/prepare_message_service_spec.rb
> +        end
just define new receiver instead of doing this

2020-04-16 08:15 UTC, drkmen commented on spec/services/trusted_drivers/messages/prepare_message_service_spec.rb
> +        end
same here

2020-04-16 08:15 UTC, drkmen commented on spec/services/trusted_drivers/messages/prepare_message_service_spec.rb
> +        end
same

2020-04-16 08:15 UTC, drkmen commented on spec/services/trusted_drivers/messages/prepare_message_service_spec.rb
> +        end
please pay attention on such little things
`let(:result_message) { 'Invite message' }`

2020-04-16 08:15 UTC, drkmen commented on spec/services/trusted_drivers/messages/prepare_message_service_spec.rb
> +        end
same

2020-04-16 08:15 UTC, drkmen commented on spec/services/trusted_drivers/messages/prepare_message_service_spec.rb
> +        end
same

2020-04-16 08:15 UTC, drkmen commented on spec/services/trusted_drivers/messages/prepare_message_service_spec.rb
> +        end
same

2020-04-16 08:15 UTC, drkmen commented on spec/services/trusted_drivers/messages/prepare_message_service_spec.rb
> +        end
please pay attention on such little things
`let(:result_message) { 'Invite message' }`

2020-04-16 08:15 UTC, drkmen commented on spec/services/trusted_drivers/messages/send_email_service_spec.rb
> +    allow_any_instance_of(TrustedDrivers::Messages::SendEmailService).to receive(:url).and_return('url')
`described_class`

2020-04-16 08:15 UTC, drkmen commented on spec/services/trusted_drivers/messages/send_email_service_spec.rb
> +  subject { TrustedDrivers::Messages::SendEmailService.perform(params) }
`described_class`

2020-04-16 08:15 UTC, drkmen commented on spec/services/trusted_drivers/requests/create_service_spec.rb
> +  subject { TrustedDrivers::Requests::CreateService.perform(params) }
`described_class`

2020-04-16 08:15 UTC, drkmen commented on spec/services/trusted_drivers/requests/delete_service_spec.rb
> +  subject { TrustedDrivers::Requests::DeleteService.perform(params) }
`described_class`

2020-04-16 08:15 UTC, drkmen commented on spec/services/trusted_drivers/requests/invitation_service_spec.rb
> +  subject { TrustedDrivers::Requests::InvitationService.perform(params) }
`described_class`

2020-04-16 08:15 UTC, drkmen commented on spec/services/trusted_drivers/user_search_service.rb
> +  subject { TrustedDrivers::UserSearchService.perform(search_params) }
`described_class`

2020-04-16 09:01 UTC, tymosVS commented on app/services/trusted_drivers/create_service.rb
> +        trusted_driver_request.update(accepted: true)
https://edgeguides.rubyonrails.org/6_0_release_notes.html#active-record-deprecations

2020-04-16 16:45 UTC, drkmen requested changes
close enough, one more little thing to fix

2020-04-16 16:45 UTC, drkmen commented on app/services/trusted_drivers/create_service.rb
> +      trusted_driver_request&.receiver_id
look, if `trusted_driver_request` was not passed, this line will return `nil`
the same as a method `requestor_id` below. 
Result will be: 
```ruby
TrustedDriver.new(trusted_driver_id: nil, trust_driver_id: nil)
```
This is not good. Please raise an error, if `trusted_driver_request` was not passed to the service

2020-04-23 05:51 UTC, drkmen approved these changes

2020-04-23 05:52 UTC, drkmen commented
@tymosVS please resolve conflicts

2020-04-23 09:40 UTC, merged